/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MbCallbackRouteImport } from './routes/mb-callback'
import { Route as IndexRouteImport } from './routes/index'

const MbCallbackRoute = MbCallbackRouteImport.update({
  id: '/mb-callback',
  path: '/mb-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mb-callback': typeof MbCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mb-callback': typeof MbCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mb-callback': typeof MbCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mb-callback'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mb-callback'
  id: '__root__' | '/' | '/mb-callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MbCallbackRoute: typeof MbCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mb-callback': {
      id: '/mb-callback'
      path: '/mb-callback'
      fullPath: '/mb-callback'
      preLoaderRoute: typeof MbCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MbCallbackRoute: MbCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
